title: "Computational Analysis of Anti-Muslim Racism in the British Empire"
description: "Exploring anti-Muslim racism in The Times through word vector models"
url: "https://clnugentmclean.github.io"
baseurl: "/dissertation"
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "air"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

markdown: kramdown
